version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:16
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
  back:
    build: .
    command: ./main
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
